const GEMINI_API_KEY = process.env.GEMINI_API_KEY || process.env.GOOGLE_GENERATIVE_AI_API_KEY;
const MODEL_NAME = "gemini-3.1-flash-image-preview"; // Nano Banana 2

interface NanoBananaParams {
  userImageBase64: string;
  userImageMimeType: string;
  garmentImageBase64: string;
  garmentImageMimeType: string;
}

export async function generateTryOnWithNanoBanana({
  userImageBase64,
  userImageMimeType,
  garmentImageBase64,
  garmentImageMimeType,
}: NanoBananaParams): Promise<string> {
  if (!GEMINI_API_KEY) {
    throw new Error("Missing GEMINI_API_KEY");
  }

  const endpoint = `https://generativelanguage.googleapis.com/v1beta/models/${MODEL_NAME}:generateContent?key=${GEMINI_API_KEY}`;

  const prompt = `Create a professional e-commerce fashion photo. Take the garment from the second image and let the person from the first image wear it. Generate a realistic, full-body shot of the person wearing the garment, with the lighting and shadows adjusted to match the environment. Ensure high-fidelity preservation of the person's facial features and the garment's texture.`;

  const payload = {
    contents: [
      {
        parts: [
          { text: prompt },
          {
            inline_data: {
              mime_type: userImageMimeType,
              data: userImageBase64,
            },
          },
          {
            inline_data: {
              mime_type: garmentImageMimeType,
              data: garmentImageBase64,
            },
          },
        ],
      },
    ],
    generationConfig: {
      responseModalities: ["IMAGE"],
    },
  };

  try {
    const response = await fetch(endpoint, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify(payload),
    });

    if (!response.ok) {
      const errorText = await response.text();
      throw new Error(`Gemini API Error: ${response.status} - ${errorText}`);
    }

    const data = await response.json();

    // The response for IMAGE modality returns the image data in the parts
    const candidates = data.candidates;
    if (!candidates || candidates.length === 0) {
      throw new Error("No image generated by Gemini");
    }

    const parts = candidates[0].content.parts;
    const imagePart = parts.find((part: any) => part.inline_data);

    if (!imagePart) {
      throw new Error("No image part found in Gemini response");
    }

    // Returns base64 data. We'll need to upload this to Supabase to get a URL
    return imagePart.inline_data.data;
  } catch (error) {
    console.error("Error in generateTryOnWithNanoBanana:", error);
    throw error;
  }
}
